### ISSUE TITLE
add a private salt to salt1

### ISSUE THREAD

**Issue by xcombelle** [comntr/webext#10]
Unless I mistake, if a salt derived from the private key is added before computing the sha1, the attack from the database described in the readme (testing thousands of urls against the hash would not work)

**Comment by comntr** [comment]
Are you suggesting to has the URLs with salt, like `H(url + salt)`? The server can still precompute the salted hashes.

**Comment by xcombelle** [comment]
Actually, a construction very similar to yours: H(salt+url) can be attacked by a kind of an length extension attack beccause depending on the length of urp, one can calculate H(salt+url+endurl) just by knowing H(salt+url) and guessing endurl and as such sever can check the end of an url if the prefix id same

From that, the problem is hader from.what I thought first and some tesearch has to be done to find an appropriate solution.
