### ISSUE TITLE
proposed description change

### ISSUE THREAD

**Issue by atomGit** [comntr/webext#2]
extension title:
consider changing the name to "**comntr - Leave a comment on any website!**" - this clarifies what the add-on does without having to read the descrip.

descrip:
Got something to say? With comntr you can leave a comment on *any website*, even if the website doesn't allow comments!

Many websites don't allow user comments, or disable comments after a certain period of time. comntr bypasses these Orwellian restrictions by allowing anyone to leave a comment on any website, as well as read comments left by others. Furthermore, your comments cannot be censored by the website administrator.

You can leave a comment or read the comments left by others by simply clicking the comntr toolbar button and writing your comment. When you visit a webpage where others have left comments, the comntr toolbar button will display a badge indicating the number of comments left and clicking the button will display all of the comments in a nice list.

comntr is an open source add-on for Firefox and Chrome that respects your right to privacy and anonymity. Please read the short and clear Privacy Policy for more details.

If you find any bugs or would like to request a feature, you may create an issue on the comntr GitHup repository: https://github.com/comntr/webext

**Comment by comntr** [comment]
Done. I've omitted the note about privacy, though:

> comntr is an open source add-on for Firefox and Chrome that respects your right to privacy and anonymity. Please read the short and clear Privacy Policy for more details.

As I've said in that other discussion, privacy policies give a false sense of security and it's better to warn users that everything they write may be used against them and for this reason they shouldn't leave any personal stuff behind.
