### ISSUE TITLE
privacy policy

### ISSUE THREAD

**Issue by atomGit** [comntr/webext#3]
just an idea for a privacy policy if interested...

hopefully something extremely simple and clear, like "comntr totally respects your right to privacy. This extension doesn't send anything anywhere other than the comments you post which are stored on comntr.live."

**Comment by comntr** [comment]
I'm generally skeptical about privacy policies as they don't protect the users from anything. But it's useful to have a canary that warns the users against posting personal data. If (when) the canary disappears, the users will know what that means. A privacy policy on the other hand gives naive users a false sense of security.

**Comment by atomGit** [comment]
i don't like privacy policies (or ToS) either - there would be no need if everyone were ethical

my reason for suggesting this was also to help promote the add-on - maybe some people won't install stuff if there's no PP? others, like me, like to see a very clear PP; "we don't collect shit now, nor will we ever"

as far as the commenters comments, i don't think anything needs to be addressed there other than perhaps mentioning that they're public

the main issue though is what data is collected by the infrastructure and how is it used? are you selling it to advertisers for example? i think a lot of people would feel warmer if they felt the developer is an ethical person

the situation here is a little complex because comntr is relying on github, which is owned by MS, and comntr.live, which i assume is run by you - i think some people would want to know what data, if any, is collected by not only by the add-on, but also this infrastructure

**Comment by comntr** [comment]
https://github.com/comntr/webext/commit/5dbdfefdffdd07465b99afaf2acb0f82ca475bc3
