### ISSUE TITLE
comment pop-up warning text - proposed change

### ISSUE THREAD

**Issue by atomGit** [comntr/webext#4]
currently:
> Don't post any personal information here. Read more.

proposed:
> All comments are public so you probably don't want to  post any personal information here! Read more.

also, the 'read more' link opens the github repo page in the pop-up iframe - that's probably/maybe not good - personally i think it should open in a new tab

**Comment by comntr** [comment]
[Done](https://github.com/comntr/comntr.github.io/commit/039f448c644532030d511b711671d831c2c5d9b1).
